// This enum was generated by Dialoguer
//	Do not modify this file, it will be overwritten by Dialoguer.
public enum DialoguerDialogues{
	DayOne_Captain = 0,
	DayOne_Pug = 1,
	DayTwo_Captain = 2,
	DayTwo_Pug = 3,
}
